// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/rbac.proto

package rbac

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Rbac service

func NewRbacEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Rbac service

type RbacService interface {
	Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error)
}

type rbacService struct {
	c    client.Client
	name string
}

func NewRbacService(name string, c client.Client) RbacService {
	return &rbacService{
		c:    c,
		name: name,
	}
}

func (c *rbacService) Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error) {
	req := c.c.NewRequest(c.name, "Rbac.Login", in)
	out := new(LoginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Rbac service

type RbacHandler interface {
	Login(context.Context, *LoginRequest, *LoginResponse) error
}

func RegisterRbacHandler(s server.Server, hdlr RbacHandler, opts ...server.HandlerOption) error {
	type rbac interface {
		Login(ctx context.Context, in *LoginRequest, out *LoginResponse) error
	}
	type Rbac struct {
		rbac
	}
	h := &rbacHandler{hdlr}
	return s.Handle(s.NewHandler(&Rbac{h}, opts...))
}

type rbacHandler struct {
	RbacHandler
}

func (h *rbacHandler) Login(ctx context.Context, in *LoginRequest, out *LoginResponse) error {
	return h.RbacHandler.Login(ctx, in, out)
}
